Follow new style

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,50 +26,52 @@ jobs:
       DYNAFLOW_LAUNCHER_LOCALE: "en_GB"
       COMPILER_FOLDER: "gcc5.3.1"
       VERSION: "1.3.0"
+      GH_API: ${{ github.api_url }}/repos/${{ github.repository }}
+      CURL_JSON: 'curl --silent --header "Content-Type": "application/json"'
 
     steps:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Fetch Dynawo
-        uses: dsaltares/fetch-gh-release-asset@master
-        with:
-          repo: "sheosi/dynawo"
-          version: "tags/nightly"
-          file: "Dynawo_headers_V${{ env.VERSION }}"
-          target: "dynawo.zip"
-          token: "${{ secrets.GITHUB_TOKEN }}"
+      - name: Fetch Dynawo and algorithms
+        run: |
+          download_asset() {
+            ASSET_URL=$( \
+              $CURL_JSON  -u "user: ${{ secrets.GITHUB_TOKEN }}"   \
+              ${{ github.api_url }}/repos/$1/releases/tags/nightly | python3 -c \
+              "import sys, json;l=[x for x in json.load(sys.stdin)['assets'] if x['name']=='$2'];print(str(l[0]['url']) if l else '')" \
+            )
+            
+            if [ ! -z $ASSET_URL ]; then
+              curl \
+                --remote-header-name \
+                --location \
+                -H "Accept: application/octet-stream" \
+                -u "user: ${{ secrets.GITHUB_TOKEN }}" \
+                "$ASSET_URL" \
+                --create-dirs \
+                --limit-rate 2M \
+                -o "$2"
+            else
+              echo "Asset not found $2 in $1"
+              exit 1
+            fi
+          }
+          
+          download_asset dynawo/dynawo Dynawo_headers_V${VERSION}.zip
+          download_asset sheosi/dynawo-algorithms Dynawo_algorithms_headers_V${VERSION}.zip
           
       - name: Extract Dynawo
         run: |
           # Does not need folder, one will be created by itself
-          unzip -qq "dynawo.zip"
+          unzip -qq "Dynawo_headers_V${VERSION}.zip"
           cd ..
-      
-      - name: Fetch Dynawo algorithms
-        uses: dsaltares/fetch-gh-release-asset@master
-        with:
-          repo: "sheosi/dynawo-algorithms"
-          version: "tags/nightly"
-          file: "dynawoAlgorithms_V${{ env.VERSION }}"
-          target: "dynawo-algorithms/dynawo-algorithms.zip"
-          token: "${{ secrets.GITHUB_TOKEN }}"
           
       - name: Extract Dynawo algorithms
         run: |
           cd dynawo-algorithms
-          unzip -qq "dynawo-algorithms.zip"
+          unzip -qq "Dynawo_algorithms_headers_V${VERSION}.zip"
           cd ..
-
-      - name: Load persistent build files
-        uses: actions/cache@v2
-        with:
-          # A list of files, directories, and wildcard patterns to cache and restore
-          path: |
-            build
-            install
-          # An explicit key for restoring and saving the cache
-          key: ${{ runner.os }}-cmake
 
       - name: Build
         run: |
